#!/usr/bin/env python3
"""
generate_redirects.py - Generate nginx redirect configuration

Creates nginx configuration files for redirecting old Docusaurus and Hugo
URLs to the new MediaWiki pages.

Usage:
    python generate_redirects.py --inventory migration_inventory.csv \
                                  --output redirect_configs/
"""

import csv
import argparse
from pathlib import Path
from typing import Dict, List


SCRIPT_DIR = Path(__file__).parent

# URL path mappings for each documentation source
DOCUSAURUS_BASE_PATHS = {
    'introduction': '/introduction',
    'getting-started': '/getting-started',
    'api-generation-and-connections': '/api-generation-and-connections',
    'Security': '/Security',
    'admin-settings': '/admin-settings',
    'system-settings': '/system-settings',
    'upgrades-and-migrations': '/upgrades-and-migrations',
    'AI': '/AI',
}

HUGO_GUIDE_PATHS = {
    'Installing and Configuring DreamFactory': '/docs/installing-and-configuring-dreamfactory',
    'Generating a Database-backed API': '/docs/generating-a-database-backed-api',
    'Advanced Database API Features': '/docs/advanced-database-api-features',
    'Authenticating Your APIs': '/docs/authenticating-your-apis',
    'Creating File System APIs': '/docs/creating-file-system-apis',
    'Creating Scripted Services': '/docs/creating-scripted-services-and-endpoints',
    'Integrating Business Logic': '/docs/integrating-business-logic-into-your-apis',
    'Using Remote HTTP and SOAP Connectors': '/docs/using-remote-http-and-soap-connectors',
    'Integrating Salesforce Data': '/docs/integrating-salesforce-data',
    'Using the System APIs': '/docs/using-the-system-apis',
    'Limiting and Logging': '/docs/limiting-and-logging-api-requests',
    'Securing Your DreamFactory': '/docs/securing-your-dreamfactory-environment',
    'Performance Considerations': '/docs/performance-considerations',
}


def source_path_to_docusaurus_url(source_path: str) -> str:
    """Convert df-docs source path to Docusaurus URL."""
    # Remove base path prefix
    path = source_path.replace('df-docs/df-docs/docs/', '')

    # Remove .md extension
    path = path.replace('.md', '')

    # Handle index files
    if path.endswith('/index') or path.endswith('/_index'):
        path = path.rsplit('/', 1)[0]

    # Convert underscores to hyphens
    path = path.replace('_', '-')

    return '/' + path


def source_path_to_hugo_url(source_path: str) -> str:
    """Convert guide source path to Hugo URL."""
    # Remove base path prefix
    path = source_path.replace('guide/dreamfactory-book-v2/content/en/docs/', '')

    # Remove .md extension and _index
    path = path.replace('.md', '').replace('/_index', '')

    # Convert spaces to hyphens, lowercase
    path = path.replace(' ', '-').lower()

    return '/docs/' + path


def wiki_page_to_url(wiki_page: str, wiki_base: str = 'https://wiki.dreamfactory.com') -> str:
    """Convert wiki page name to full URL."""
    # Replace spaces with underscores
    page_name = wiki_page.replace(' ', '_')
    return f"{wiki_base}/wiki/{page_name}"


def generate_nginx_config(
    redirects: List[Dict[str, str]],
    server_name: str,
    output_file: str
):
    """Generate nginx server block configuration."""

    config_lines = [
        f"# Redirect configuration for {server_name}",
        f"# Generated by generate_redirects.py",
        f"# Total redirects: {len(redirects)}",
        "",
        "server {",
        "    listen 80;",
        "    listen 443 ssl;",
        f"    server_name {server_name};",
        "",
        "    # SSL configuration (adjust paths as needed)",
        "    # ssl_certificate /etc/letsencrypt/live/{server_name}/fullchain.pem;",
        "    # ssl_certificate_key /etc/letsencrypt/live/{server_name}/privkey.pem;",
        "",
        "    # Specific path redirects",
    ]

    # Add specific redirects
    for redirect in redirects:
        old_path = redirect['old_path']
        new_url = redirect['new_url']
        config_lines.append(f"    location = {old_path} {{")
        config_lines.append(f"        return 301 {new_url};")
        config_lines.append("    }")
        config_lines.append("")

    # Add catch-all redirect
    config_lines.extend([
        "    # Catch-all redirect to wiki main page",
        "    location / {",
        "        return 301 https://wiki.dreamfactory.com/wiki/Main_Page;",
        "    }",
        "}",
    ])

    # Write config
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(config_lines))

    print(f"Generated: {output_file}")


def generate_apache_config(
    redirects: List[Dict[str, str]],
    server_name: str,
    output_file: str
):
    """Generate Apache .htaccess redirect rules."""

    config_lines = [
        f"# Redirect configuration for {server_name}",
        f"# Generated by generate_redirects.py",
        f"# Total redirects: {len(redirects)}",
        "",
        "RewriteEngine On",
        "",
        "# Specific path redirects",
    ]

    for redirect in redirects:
        old_path = redirect['old_path']
        new_url = redirect['new_url']
        # Escape special regex characters in path
        escaped_path = old_path.replace('.', r'\.').replace('-', r'\-')
        config_lines.append(f"RewriteRule ^{escaped_path.lstrip('/')}$ {new_url} [R=301,L]")

    # Add catch-all
    config_lines.extend([
        "",
        "# Catch-all redirect to wiki main page",
        "RewriteRule ^.*$ https://wiki.dreamfactory.com/wiki/Main_Page [R=301,L]",
    ])

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(config_lines))

    print(f"Generated: {output_file}")


def generate_redirect_map(redirects: List[Dict[str, str]], output_file: str):
    """Generate a simple redirect map CSV."""

    with open(output_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=['source', 'old_path', 'new_url', 'wiki_page'])
        writer.writeheader()
        writer.writerows(redirects)

    print(f"Generated: {output_file}")


def main():
    parser = argparse.ArgumentParser(description='Generate URL redirect configurations')
    parser.add_argument('--inventory', '-i', default='migration_inventory.csv',
                        help='Migration inventory CSV')
    parser.add_argument('--output', '-o', default='redirect_configs',
                        help='Output directory for config files')
    parser.add_argument('--wiki-base', '-w', default='https://wiki.dreamfactory.com',
                        help='Base URL for wiki')
    parser.add_argument('--format', '-f', choices=['nginx', 'apache', 'all'], default='all',
                        help='Config format to generate')

    args = parser.parse_args()

    inventory_path = SCRIPT_DIR / args.inventory
    output_dir = SCRIPT_DIR / args.output

    # Create output directory
    output_dir.mkdir(exist_ok=True)

    # Load inventory
    if not inventory_path.exists():
        print(f"Error: Inventory file not found: {inventory_path}")
        print("Run inventory.py first to generate the inventory")
        return 1

    with open(inventory_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        inventory = list(reader)

    print(f"Loaded {len(inventory)} items from inventory")

    # Generate redirects for each source type
    docusaurus_redirects = []
    hugo_redirects = []

    for item in inventory:
        source_path = item.get('source_path', '')
        source_type = item.get('source_type', '')
        wiki_page = item.get('target_wiki_page', '')

        if not wiki_page:
            continue

        if source_type == 'df-docs':
            old_path = source_path_to_docusaurus_url(source_path)
            new_url = wiki_page_to_url(wiki_page, args.wiki_base)
            docusaurus_redirects.append({
                'source': source_path,
                'old_path': old_path,
                'new_url': new_url,
                'wiki_page': wiki_page
            })

        elif source_type == 'guide':
            old_path = source_path_to_hugo_url(source_path)
            new_url = wiki_page_to_url(wiki_page, args.wiki_base)
            hugo_redirects.append({
                'source': source_path,
                'old_path': old_path,
                'new_url': new_url,
                'wiki_page': wiki_page
            })

    print(f"\nGenerated {len(docusaurus_redirects)} Docusaurus redirects")
    print(f"Generated {len(hugo_redirects)} Hugo guide redirects")

    # Generate config files
    if args.format in ('nginx', 'all'):
        if docusaurus_redirects:
            generate_nginx_config(
                docusaurus_redirects,
                'docs.dreamfactory.com',
                str(output_dir / 'docs-dreamfactory-com.nginx.conf')
            )
        if hugo_redirects:
            generate_nginx_config(
                hugo_redirects,
                'guide.dreamfactory.com',
                str(output_dir / 'guide-dreamfactory-com.nginx.conf')
            )

    if args.format in ('apache', 'all'):
        if docusaurus_redirects:
            generate_apache_config(
                docusaurus_redirects,
                'docs.dreamfactory.com',
                str(output_dir / 'docs-dreamfactory-com.htaccess')
            )
        if hugo_redirects:
            generate_apache_config(
                hugo_redirects,
                'guide.dreamfactory.com',
                str(output_dir / 'guide-dreamfactory-com.htaccess')
            )

    # Always generate redirect map CSV
    all_redirects = docusaurus_redirects + hugo_redirects
    generate_redirect_map(all_redirects, str(output_dir / 'redirect_map.csv'))

    print(f"\nAll configurations written to: {output_dir}/")


if __name__ == '__main__':
    exit(main() or 0)
